


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."account_type" AS ENUM (
    'checking',
    'savings',
    'credit_card',
    'cash'
);


ALTER TYPE "public"."account_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  -- Insert the profile, but do NOT fail if it already exists or if data is missing
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email)
  ON CONFLICT (id) DO NOTHING;
  
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_account_balance"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  -- Handle Insert
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.accounts
    SET current_balance_cents = current_balance_cents + NEW.amount_cents
    WHERE id = NEW.account_id;
  
  -- Handle Delete
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.accounts
    SET current_balance_cents = current_balance_cents - OLD.amount_cents
    WHERE id = OLD.account_id;
  END IF;
  RETURN NULL;
END;
$$;


ALTER FUNCTION "public"."update_account_balance"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "type" "public"."account_type" NOT NULL,
    "current_balance_cents" bigint DEFAULT 0,
    "is_liability" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."allocation_buckets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "name" "text" NOT NULL,
    "percentage" numeric DEFAULT 0,
    "target_amount" numeric DEFAULT 0,
    "current_amount" numeric DEFAULT 0,
    "color_hex" "text" DEFAULT '#4A5D4E'::"text",
    "current_balance" numeric DEFAULT 0
);


ALTER TABLE "public"."allocation_buckets" OWNER TO "postgres";


ALTER TABLE "public"."allocation_buckets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."allocation_buckets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."allocation_categories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "target_amount_cents" bigint DEFAULT 0,
    "is_fixed" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."allocation_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."allocations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "category_id" "uuid" NOT NULL,
    "allocated_amount_cents" bigint DEFAULT 0,
    "spent_amount_cents" bigint DEFAULT 0,
    "pay_period_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."allocations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."income_sources" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "default_amount_cents" bigint DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."income_sources" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."income_transactions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "source_id" "uuid",
    "pay_period_id" "uuid",
    "amount_cents" bigint NOT NULL,
    "received_date" "date" DEFAULT CURRENT_DATE,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."income_transactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pay_periods" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "is_closed" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_current" boolean DEFAULT false,
    CONSTRAINT "valid_date_range" CHECK (("end_date" >= "start_date"))
);


ALTER TABLE "public"."pay_periods" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "website" "text",
    "email" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subscription_plans" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "price" numeric(10,2) NOT NULL,
    "currency" "text" DEFAULT 'USD'::"text",
    "interval" "text" DEFAULT 'month'::"text",
    "trial_days" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."subscription_plans" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "account_id" "uuid" NOT NULL,
    "allocation_id" "uuid",
    "amount_cents" bigint NOT NULL,
    "description" "text",
    "transaction_date" "date" DEFAULT CURRENT_DATE,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "plan_id" "uuid",
    "status" "text" NOT NULL,
    "trial_start_date" timestamp with time zone,
    "trial_end_date" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "user_subscriptions_status_check" CHECK (("status" = ANY (ARRAY['trialing'::"text", 'active'::"text", 'past_due'::"text", 'canceled'::"text", 'unpaid'::"text"])))
);


ALTER TABLE "public"."user_subscriptions" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."view_pay_period_summary" AS
 SELECT "id" AS "pay_period_id",
    "user_id",
    "start_date",
    "end_date",
    "is_closed",
    COALESCE(( SELECT "sum"("it"."amount_cents") AS "sum"
           FROM "public"."income_transactions" "it"
          WHERE ("it"."pay_period_id" = "pp"."id")), (0)::numeric) AS "total_income",
    COALESCE(( SELECT "sum"("a"."allocated_amount_cents") AS "sum"
           FROM "public"."allocations" "a"
          WHERE ("a"."pay_period_id" = "pp"."id")), (0)::numeric) AS "total_allocated",
    COALESCE(( SELECT "sum"("a"."spent_amount_cents") AS "sum"
           FROM "public"."allocations" "a"
          WHERE ("a"."pay_period_id" = "pp"."id")), (0)::numeric) AS "total_spent"
   FROM "public"."pay_periods" "pp";


ALTER VIEW "public"."view_pay_period_summary" OWNER TO "postgres";


ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."allocation_buckets"
    ADD CONSTRAINT "allocation_buckets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."allocation_categories"
    ADD CONSTRAINT "allocation_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."allocations"
    ADD CONSTRAINT "allocations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."income_sources"
    ADD CONSTRAINT "income_sources_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."income_transactions"
    ADD CONSTRAINT "income_transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pay_periods"
    ADD CONSTRAINT "pay_periods_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."subscription_plans"
    ADD CONSTRAINT "subscription_plans_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."allocations"
    ADD CONSTRAINT "unique_allocation_per_period" UNIQUE ("pay_period_id", "category_id");



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_allocations_pay_period" ON "public"."allocations" USING "btree" ("pay_period_id");



CREATE INDEX "idx_pay_periods_dates" ON "public"."pay_periods" USING "btree" ("user_id", "start_date");



CREATE INDEX "idx_transactions_user_id" ON "public"."transactions" USING "btree" ("user_id");



CREATE OR REPLACE TRIGGER "handle_updated_at" BEFORE UPDATE ON "public"."accounts" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');



CREATE OR REPLACE TRIGGER "trigger_update_balance" AFTER INSERT OR DELETE ON "public"."transactions" FOR EACH ROW EXECUTE FUNCTION "public"."update_account_balance"();



ALTER TABLE ONLY "public"."allocation_buckets"
    ADD CONSTRAINT "allocation_buckets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."allocations"
    ADD CONSTRAINT "allocations_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."allocation_categories"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."allocations"
    ADD CONSTRAINT "fk_allocations_pay_period" FOREIGN KEY ("pay_period_id") REFERENCES "public"."pay_periods"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."income_transactions"
    ADD CONSTRAINT "fk_income_pay_period" FOREIGN KEY ("pay_period_id") REFERENCES "public"."pay_periods"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."income_transactions"
    ADD CONSTRAINT "income_transactions_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."income_sources"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_allocation_id_fkey" FOREIGN KEY ("allocation_id") REFERENCES "public"."allocations"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."subscription_plans"("id");



ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Public read access for plans" ON "public"."subscription_plans" FOR SELECT USING (true);



CREATE POLICY "Users can delete own buckets" ON "public"."allocation_buckets" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own buckets" ON "public"."allocation_buckets" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can isolate accounts" ON "public"."accounts" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate allocations" ON "public"."allocations" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate categories" ON "public"."allocation_categories" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate income sources" ON "public"."income_sources" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate income transactions" ON "public"."income_transactions" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate pay periods" ON "public"."pay_periods" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can isolate transactions" ON "public"."transactions" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own buckets" ON "public"."allocation_buckets" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can view own buckets" ON "public"."allocation_buckets" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own subscription" ON "public"."user_subscriptions" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."allocation_buckets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."allocation_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."allocations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."income_sources" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."income_transactions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pay_periods" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscription_plans" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_subscriptions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_account_balance"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_account_balance"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_account_balance"() TO "service_role";


















GRANT ALL ON TABLE "public"."accounts" TO "anon";
GRANT ALL ON TABLE "public"."accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts" TO "service_role";



GRANT ALL ON TABLE "public"."allocation_buckets" TO "anon";
GRANT ALL ON TABLE "public"."allocation_buckets" TO "authenticated";
GRANT ALL ON TABLE "public"."allocation_buckets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."allocation_buckets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."allocation_buckets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."allocation_buckets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."allocation_categories" TO "anon";
GRANT ALL ON TABLE "public"."allocation_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."allocation_categories" TO "service_role";



GRANT ALL ON TABLE "public"."allocations" TO "anon";
GRANT ALL ON TABLE "public"."allocations" TO "authenticated";
GRANT ALL ON TABLE "public"."allocations" TO "service_role";



GRANT ALL ON TABLE "public"."income_sources" TO "anon";
GRANT ALL ON TABLE "public"."income_sources" TO "authenticated";
GRANT ALL ON TABLE "public"."income_sources" TO "service_role";



GRANT ALL ON TABLE "public"."income_transactions" TO "anon";
GRANT ALL ON TABLE "public"."income_transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."income_transactions" TO "service_role";



GRANT ALL ON TABLE "public"."pay_periods" TO "anon";
GRANT ALL ON TABLE "public"."pay_periods" TO "authenticated";
GRANT ALL ON TABLE "public"."pay_periods" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."subscription_plans" TO "anon";
GRANT ALL ON TABLE "public"."subscription_plans" TO "authenticated";
GRANT ALL ON TABLE "public"."subscription_plans" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON TABLE "public"."user_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."user_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."user_subscriptions" TO "service_role";



GRANT ALL ON TABLE "public"."view_pay_period_summary" TO "anon";
GRANT ALL ON TABLE "public"."view_pay_period_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."view_pay_period_summary" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();








